# We need to use conda here because we need to build python with
# the correct sqlite version.

language: python

python:
  - 3.6

before_install:
  - export MINICONDA=${HOME}/miniconda
  - export PATH=${MINICONDA}/bin:${PATH}
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p ${MINICONDA}
  - conda config --set always_yes yes
  - conda env create -n my_env -f envs/create_db.yml
  - source activate my_env
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  - python --version
  - flake8 src tests
  - coverage run --source=src -m py.test -v tests
  - coverage xml

after_success:
  - codecov